version: '3.6'

services:
  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3002:3002
      - 9229:9229
    command: /bin/sh -c "npm install && npm run dev"
    environment:
      - SENTRY_DSN=https://ac855a133b59484eae32ac5ce34a814c@o336427.ingest.sentry.io/5685201
