version: '3.6'

services:
  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: /bin/sh -c "npm install && npm run dev"
    networks:
      - lendit_gateway

networks:
  lendit_gateway:
    driver: 'bridge'
    name: lendit_gateway
